inputs:
  env:
    type: string
    enum:
      - env:dev
      - env:prod
      - env:test
    default: env:dev
    title: Environment
    description: Target Environment
  size:
    type: string
    enum:
      - small
      - medium
      - large
    description: Size of Nodes
    title: Tier Machine Size
  username:
    type: string
    minLength: 4
    maxLength: 20
    pattern: '[a-z]+'
    title: Database Username
    description: Database Username
  userpassword:
    type: string
    pattern: '[a-z0-9A-Z@#$]+'
    encrypted: true
    title: Database Password
    description: Database Password
  databaseDiskSize:
    type: number
    default: 4
    maximum: 10
    title: MySQL Data Disk Size
    description: Database Disk Size
  resoruceGroup:
    type: string
    title: Resource Group Name
resources:
  Cloud_Azure_ResourceGroup_1:
    type: Cloud.Azure.ResourceGroup
    metadata:
      layoutPosition:
        - 0
        - 1
    properties:
      name: ${input.resoruceGroup}
      useExisting: false
      tags:
        - key: env
          value: dev
  Cloud_Service_Azure_SQL_Database_1:
    type: Cloud.Service.Azure.SQL.Database
    dependsOn:
      - Cloud_Service_Azure_SQL_Server_1
      - Cloud_Azure_ResourceGroup_1
    metadata:
      layoutPosition:
        - 0
        - 2
    properties:
      name: vcacdb01
      region: East US
      account: Azure-Prem-Temp
      server_name: premsqldb
      resource_group_name: ${input.resoruceGroup}
      tags:
        env: dev
  Cloud_Service_Azure_SQL_Server_1:
    type: Cloud.Service.Azure.SQL.Server
    dependsOn:
      - WP-Network-Private
      - Cloud_Azure_ResourceGroup_1
    metadata:
      layoutPosition:
        - 0
        - 3
    properties:
      name: premsqldb
      region: East US
      account: Azure-Prem-Temp
      version: '12.0'
      administrator_login: sqladmin
      resource_group_name: ${input.resoruceGroup}
      administrator_login_password: P@ssw0rd
      tags:
        env: dev
  WP-Network-Private:
    type: Cloud.Network
    dependsOn:
      - Cloud_Azure_ResourceGroup_1
    metadata:
      layoutPosition:
        - 1
        - 0
    properties:
      name: null
      networkType: existing
      constraints:
        - tag: ${input.env}
